// Mock data for assets (unchanged)
export const mockAssets = [
  {
    id: "AST-001",
    name: "HVAC Unit",
    location: "Building A - Roof",
    status: "Online",
    isOnline: true,
    icon: "🏠",
    criticality: "High",
    manufacturer: "Siemens",
    model: "dpr123",
  },
  {
    id: "AST-002",
    name: "Boiler #1",
    location: "Basement - Mechanical Room",
    status: "Online",
    isOnline: true,
    icon: "🔥",
    criticality: "Critical",
    manufacturer: "Viessmann",
    model: "B200H-80",
  },
  {
    id: "AST-003",
    name: "Emergency Generator",
    location: "Building B - Generator Room",
    status: "Offline",
    isOnline: false,
    icon: "⚡",
    criticality: "Critical",
    manufacturer: "Caterpillar",
    model: "C18-ACERT",
  },
  {
    id: "AST-004",
    name: "Water Pump #1",
    location: "Basement - Pump Room",
    status: "Online",
    isOnline: true,
    icon: "💧",
    criticality: "High",
    manufacturer: "Grundfos",
    model: "CR64-2-2",
  },
  {
    id: "AST-005",
    name: "Air Compressor",
    location: "Warehouse - Equipment Bay",
    status: "Online",
    isOnline: true,
    icon: "🌀",
    criticality: "Medium",
    manufacturer: "Atlas Copco",
    model: "GA30VSD",
  },
  {
    id: "AST-006",
    name: "Elevator Motor",
    location: "Building A - Elevator Shaft",
    status: "Maintenance",
    isOnline: false,
    icon: "🏗️",
    criticality: "High",
    manufacturer: "Otis",
    model: "GeN2-MR",
  },
  {
    id: "AST-007",
    name: "Cooling Tower",
    location: "Roof - West Side",
    status: "Online",
    isOnline: true,
    icon: "❄️",
    criticality: "High",
    manufacturer: "Baltimore Aircoil",
    model: "VTI-1500",
  },
  {
    id: "AST-008",
    name: "Industrial Chiller",
    location: "Building B - HVAC Room",
    status: "Online",
    isOnline: true,
    icon: "🧊",
    criticality: "Critical",
    manufacturer: "Trane",
    model: "CVHF-2000",
  },
  {
    id: "AST-009",
    name: "Lighting Control Panel",
    location: "Building A - Electrical Room",
    status: "Online",
    isOnline: true,
    icon: "💡",
    criticality: "Low",
    manufacturer: "Lutron",
    model: "HomeWorks QS",
  },
  {
    id: "AST-010",
    name: "Fire Pump",
    location: "Basement - Fire Protection",
    status: "Online",
    isOnline: true,
    icon: "🚨",
    criticality: "Critical",
    manufacturer: "Pentair",
    model: "Aurora 4280",
  },
  {
    id: "AST-011",
    name: "UPS System",
    location: "Building A - Server Room",
    status: "Online",
    isOnline: true,
    icon: "🔋",
    criticality: "Critical",
    manufacturer: "APC",
    model: "Galaxy 7000",
  },
  {
    id: "AST-012",
    name: "Conveyor Belt #3",
    location: "Warehouse - Production Line",
    status: "Offline",
    isOnline: false,
    icon: "📦",
    criticality: "Medium",
    manufacturer: "Dorner",
    model: "2200 Series",
  },
  {
    id: "AST-013",
    name: "Steam Boiler",
    location: "Building C - Mechanical",
    status: "Online",
    isOnline: true,
    icon: "♨️",
    criticality: "High",
    manufacturer: "Cleaver-Brooks",
    model: "CB-700-300",
  },
  {
    id: "AST-014",
    name: "Waste Water Pump",
    location: "Basement - Utility Room",
    status: "Online",
    isOnline: true,
    icon: "🌊",
    criticality: "Medium",
    manufacturer: "Flygt",
    model: "3127.171",
  },
  {
    id: "AST-015",
    name: "Transformer #2",
    location: "Electrical Yard",
    status: "Online",
    isOnline: true,
    icon: "⚡",
    criticality: "Critical",
    manufacturer: "ABB",
    model: "ONAN-1500",
  },
];
